# Generated by Django 5.2.3 on 2025-06-27 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0003_amenity_remove_roomtype_hotel'),
    ]

    operations = [
        migrations.AddField(
            model_name='roomtype',
            name='amenities',
            field=models.ManyToManyField(to='rooms.amenity'),
        ),
    ]
