# Generated by Django 5.2.3 on 2025-07-01 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0004_roomtype_amenities'),
    ]

    operations = [
        migrations.RenameField(
            model_name='roomtype',
            old_name='capacity',
            new_name='total_rooms',
        ),
        migrations.AddField(
            model_name='roomtype',
            name='total_adults',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='roomtype',
            name='total_children',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
