# Generated by Django 5.2.3 on 2025-06-26 07:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0003_hotel_image_hotel_images'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hotel',
            name='images',
        ),
        migrations.DeleteModel(
            name='Hotel_Image',
        ),
    ]
