# Generated by Django 5.2.3 on 2025-06-26 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0005_hotel_image_hotel_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel_image',
            name='image',
            field=models.ImageField(upload_to='hotel_images/'),
        ),
    ]
