# Generated by Django 5.2.3 on 2025-06-26 08:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0006_alter_hotel_image_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hotel',
            name='images',
        ),
        migrations.DeleteModel(
            name='Hotel_Image',
        ),
    ]
