# Generated by Django 5.2.3 on 2025-07-01 11:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('booking', '0001_initial'),
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='payment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='booking_payment', to='payment.payment'),
        ),
        migrations.AlterUniqueTogether(
            name='meal',
            unique_together={('date', 'meal_type')},
        ),
        migrations.AddField(
            model_name='booking',
            name='meal_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='booking.meal'),
        ),
    ]
